name: Qodana Code Inspection

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2024.1
        with:
          project-dir: .
          upload-result: true
          pr-comment: true